# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

name: Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  schedule:
    - cron: "57 0 * * *" # Daily at 00:57 UTC
  # Triggered on push to branch "main" by .github/workflows/release.yaml
  workflow_call:
    outputs:
      artifact-prefix:
        description: build_charm.yaml `artifact-prefix` output
        value: ${{ jobs.build.outputs.artifact-prefix }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install tox & poetry
        run: |
          pipx install tox
          pipx install poetry
      - name: Run linters
        run: |
          tox run -e lint

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install tox & poetry
        run: |
          pipx install tox
          pipx install poetry
      - name: Run tests
        run: |
          tox run -vve unit

  build:
    strategy:
      matrix:
        path:
          - .
          - tests/integration/test-charm-azure-service-principal
    name: Build charm | ${{ matrix.path }}
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@v29.2.0
    with:
      path-to-charm-directory: ${{ matrix.path }}
      cache: false

  release-to-test-branch:
    name: Release charm to test branch
    if: ${{ github.event_name == 'pull_request' }}
    needs:
      - build
    uses: canonical/data-platform-workflows/.github/workflows/release_charm_pr.yaml@v42.1.0
    with:
      track: "1"
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
    secrets:
      charmhub-token: ${{ secrets.CHARMHUB_TOKEN }}
    permissions:
      contents: write # Needed to create git tags

  integration-test:
    name: Run charm integration tests
    needs:
      - lint
      - build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup environment
        run: |
          sudo apt-get remove -y docker-ce docker-ce-cli containerd.io
          sudo rm -rf /run/containerd
          sudo snap install concierge --classic
          sudo concierge prepare --trace
      - name: Download packed charm(s)
        uses: actions/download-artifact@v5
        with:
          artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
          merge-multiple: true
      - name: Install tox & poetry
        run: |
          pipx install tox
          pipx install poetry
      - name: Run integration tests
        run: tox -e integration


      - name: Get pod statuses
        run: kubectl get all -A
        if: failure()

      - name: Get juju status
        run: juju status
        if: failure()

      - name: Get azure-auth-integrator operator logs
        run: kubectl logs --tail 100 -nkubeflow -loperator.juju.is/name=azure-auth-integrator
        if: failure()
